### PR TITLE
Add an option in config to disable the 1.9 attack cooldown

### PR DESCRIPTION
**Pull request by Ultra03**
Tested on 1.13.2. Jar located [here](https://mega.nz/#!3h5xjCLb!oLccADyn-55cLFi-kUrIA-f5_RXTEDfJqFmANV5yu8o) for convenience if needed.

### CODE REVIEW

**Review by cmastudios — CHANGES_REQUESTED** [review]
I feel like we should only change the attack speed for players while they are playing in a warzone.

**Comment by Ultra03** [comment]
Alright, I can work on that.

**Comment by Ultra03** [comment]
@cmastudios Done!

**Comment by cmastudios** [comment]
Nice I’ll test in a bit. Future note: I wonder if any other plugins modify the base attack speed enough that it would be worth it to save and restore.

**Comment by Ultra03** [comment]
If we need to, sure. We could use a HashMap that stores the Player and their attack speed before it gets modified by War, and then bump it up to 1024. Then we just reset it to the value stored in the HashMap instead of setting it to 4.0.

**Review by cmastudios — APPROVED** [review]

**Pull request merged**
